// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Turtle.Contract.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Turtle.CompiledModels
{
    public static class CredentialEntityUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref Guid Id(CredentialEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CustomAvailableCharacters>k__BackingField")]
        public static extern ref string CustomAvailableCharacters(CredentialEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsAvailableLowerLatin>k__BackingField")]
        public static extern ref bool IsAvailableLowerLatin(CredentialEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsAvailableNumber>k__BackingField")]
        public static extern ref bool IsAvailableNumber(CredentialEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsAvailableSpecialSymbols>k__BackingField")]
        public static extern ref bool IsAvailableSpecialSymbols(CredentialEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsAvailableUpperLatin>k__BackingField")]
        public static extern ref bool IsAvailableUpperLatin(CredentialEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Key>k__BackingField")]
        public static extern ref string Key(CredentialEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Length>k__BackingField")]
        public static extern ref ushort Length(CredentialEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Login>k__BackingField")]
        public static extern ref string Login(CredentialEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(CredentialEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<OrderIndex>k__BackingField")]
        public static extern ref uint OrderIndex(CredentialEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ParentId>k__BackingField")]
        public static extern ref Guid? ParentId(CredentialEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Regex>k__BackingField")]
        public static extern ref string Regex(CredentialEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Type>k__BackingField")]
        public static extern ref CredentialType Type(CredentialEntity @this);
    }
}
