// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Turtle.Contract.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Turtle
{
    [EntityFrameworkInternal]
    public partial class CredentialEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Turtle.Contract.Models.CredentialEntity",
                typeof(CredentialEntity),
                baseEntityType,
                propertyCount: 14,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(CredentialEntity).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CredentialEntity).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));

            var customAvailableCharacters = runtimeEntityType.AddProperty(
                "CustomAvailableCharacters",
                typeof(string),
                propertyInfo: typeof(CredentialEntity).GetProperty("CustomAvailableCharacters", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CredentialEntity).GetField("<CustomAvailableCharacters>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var isAvailableLowerLatin = runtimeEntityType.AddProperty(
                "IsAvailableLowerLatin",
                typeof(bool),
                propertyInfo: typeof(CredentialEntity).GetProperty("IsAvailableLowerLatin", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CredentialEntity).GetField("<IsAvailableLowerLatin>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var isAvailableNumber = runtimeEntityType.AddProperty(
                "IsAvailableNumber",
                typeof(bool),
                propertyInfo: typeof(CredentialEntity).GetProperty("IsAvailableNumber", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CredentialEntity).GetField("<IsAvailableNumber>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var isAvailableSpecialSymbols = runtimeEntityType.AddProperty(
                "IsAvailableSpecialSymbols",
                typeof(bool),
                propertyInfo: typeof(CredentialEntity).GetProperty("IsAvailableSpecialSymbols", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CredentialEntity).GetField("<IsAvailableSpecialSymbols>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var isAvailableUpperLatin = runtimeEntityType.AddProperty(
                "IsAvailableUpperLatin",
                typeof(bool),
                propertyInfo: typeof(CredentialEntity).GetProperty("IsAvailableUpperLatin", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CredentialEntity).GetField("<IsAvailableUpperLatin>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var key = runtimeEntityType.AddProperty(
                "Key",
                typeof(string),
                propertyInfo: typeof(CredentialEntity).GetProperty("Key", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CredentialEntity).GetField("<Key>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 255);

            var length = runtimeEntityType.AddProperty(
                "Length",
                typeof(ushort),
                propertyInfo: typeof(CredentialEntity).GetProperty("Length", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CredentialEntity).GetField("<Length>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: (ushort)0);

            var login = runtimeEntityType.AddProperty(
                "Login",
                typeof(string),
                propertyInfo: typeof(CredentialEntity).GetProperty("Login", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CredentialEntity).GetField("<Login>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 255);

            var name = runtimeEntityType.AddProperty(
                "Name",
                typeof(string),
                propertyInfo: typeof(CredentialEntity).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CredentialEntity).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 255);

            var orderIndex = runtimeEntityType.AddProperty(
                "OrderIndex",
                typeof(uint),
                propertyInfo: typeof(CredentialEntity).GetProperty("OrderIndex", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CredentialEntity).GetField("<OrderIndex>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0u);

            var parentId = runtimeEntityType.AddProperty(
                "ParentId",
                typeof(Guid?),
                propertyInfo: typeof(CredentialEntity).GetProperty("ParentId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CredentialEntity).GetField("<ParentId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var regex = runtimeEntityType.AddProperty(
                "Regex",
                typeof(string),
                propertyInfo: typeof(CredentialEntity).GetProperty("Regex", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CredentialEntity).GetField("<Regex>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 255);

            var type = runtimeEntityType.AddProperty(
                "Type",
                typeof(CredentialType),
                propertyInfo: typeof(CredentialEntity).GetProperty("Type", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CredentialEntity).GetField("<Type>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            type.SetSentinelFromProviderValue((byte)0);

            var key0 = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key0);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "CredentialEntity");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
