// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Nestor.Db.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Turtle
{
    [EntityFrameworkInternal]
    public partial class EventEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Nestor.Db.Models.EventEntity",
                typeof(EventEntity),
                baseEntityType,
                propertyCount: 28,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(long),
                propertyInfo: typeof(EventEntity).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EventEntity).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0L);

            var createdAt = runtimeEntityType.AddProperty(
                "CreatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(EventEntity).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EventEntity).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));

            var entityBooleanValue = runtimeEntityType.AddProperty(
                "EntityBooleanValue",
                typeof(bool?),
                propertyInfo: typeof(EventEntity).GetProperty("EntityBooleanValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EventEntity).GetField("<EntityBooleanValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var entityByteArrayValue = runtimeEntityType.AddProperty(
                "EntityByteArrayValue",
                typeof(byte[]),
                propertyInfo: typeof(EventEntity).GetProperty("EntityByteArrayValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EventEntity).GetField("<EntityByteArrayValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var entityByteValue = runtimeEntityType.AddProperty(
                "EntityByteValue",
                typeof(byte?),
                propertyInfo: typeof(EventEntity).GetProperty("EntityByteValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EventEntity).GetField("<EntityByteValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var entityCharValue = runtimeEntityType.AddProperty(
                "EntityCharValue",
                typeof(char?),
                propertyInfo: typeof(EventEntity).GetProperty("EntityCharValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EventEntity).GetField("<EntityCharValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var entityDateOnlyValue = runtimeEntityType.AddProperty(
                "EntityDateOnlyValue",
                typeof(DateOnly?),
                propertyInfo: typeof(EventEntity).GetProperty("EntityDateOnlyValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EventEntity).GetField("<EntityDateOnlyValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var entityDateTimeOffsetValue = runtimeEntityType.AddProperty(
                "EntityDateTimeOffsetValue",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(EventEntity).GetProperty("EntityDateTimeOffsetValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EventEntity).GetField("<EntityDateTimeOffsetValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var entityDateTimeValue = runtimeEntityType.AddProperty(
                "EntityDateTimeValue",
                typeof(DateTime?),
                propertyInfo: typeof(EventEntity).GetProperty("EntityDateTimeValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EventEntity).GetField("<EntityDateTimeValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var entityDecimalValue = runtimeEntityType.AddProperty(
                "EntityDecimalValue",
                typeof(decimal?),
                propertyInfo: typeof(EventEntity).GetProperty("EntityDecimalValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EventEntity).GetField("<EntityDecimalValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var entityDoubleValue = runtimeEntityType.AddProperty(
                "EntityDoubleValue",
                typeof(double?),
                propertyInfo: typeof(EventEntity).GetProperty("EntityDoubleValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EventEntity).GetField("<EntityDoubleValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var entityGuidValue = runtimeEntityType.AddProperty(
                "EntityGuidValue",
                typeof(Guid?),
                propertyInfo: typeof(EventEntity).GetProperty("EntityGuidValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EventEntity).GetField("<EntityGuidValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var entityId = runtimeEntityType.AddProperty(
                "EntityId",
                typeof(Guid),
                propertyInfo: typeof(EventEntity).GetProperty("EntityId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EventEntity).GetField("<EntityId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));

            var entityInt16Value = runtimeEntityType.AddProperty(
                "EntityInt16Value",
                typeof(short?),
                propertyInfo: typeof(EventEntity).GetProperty("EntityInt16Value", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EventEntity).GetField("<EntityInt16Value>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var entityInt32Value = runtimeEntityType.AddProperty(
                "EntityInt32Value",
                typeof(int?),
                propertyInfo: typeof(EventEntity).GetProperty("EntityInt32Value", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EventEntity).GetField("<EntityInt32Value>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var entityInt64Value = runtimeEntityType.AddProperty(
                "EntityInt64Value",
                typeof(long?),
                propertyInfo: typeof(EventEntity).GetProperty("EntityInt64Value", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EventEntity).GetField("<EntityInt64Value>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var entityProperty = runtimeEntityType.AddProperty(
                "EntityProperty",
                typeof(string),
                propertyInfo: typeof(EventEntity).GetProperty("EntityProperty", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EventEntity).GetField("<EntityProperty>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 255);

            var entitySByteValue = runtimeEntityType.AddProperty(
                "EntitySByteValue",
                typeof(sbyte?),
                propertyInfo: typeof(EventEntity).GetProperty("EntitySByteValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EventEntity).GetField("<EntitySByteValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var entitySingleValue = runtimeEntityType.AddProperty(
                "EntitySingleValue",
                typeof(float?),
                propertyInfo: typeof(EventEntity).GetProperty("EntitySingleValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EventEntity).GetField("<EntitySingleValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var entityStringValue = runtimeEntityType.AddProperty(
                "EntityStringValue",
                typeof(string),
                propertyInfo: typeof(EventEntity).GetProperty("EntityStringValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EventEntity).GetField("<EntityStringValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var entityTimeOnlyValue = runtimeEntityType.AddProperty(
                "EntityTimeOnlyValue",
                typeof(TimeOnly?),
                propertyInfo: typeof(EventEntity).GetProperty("EntityTimeOnlyValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EventEntity).GetField("<EntityTimeOnlyValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var entityTimeSpanValue = runtimeEntityType.AddProperty(
                "EntityTimeSpanValue",
                typeof(TimeSpan?),
                propertyInfo: typeof(EventEntity).GetProperty("EntityTimeSpanValue", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EventEntity).GetField("<EntityTimeSpanValue>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var entityType = runtimeEntityType.AddProperty(
                "EntityType",
                typeof(string),
                propertyInfo: typeof(EventEntity).GetProperty("EntityType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EventEntity).GetField("<EntityType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 255);

            var entityUInt16Value = runtimeEntityType.AddProperty(
                "EntityUInt16Value",
                typeof(ushort?),
                propertyInfo: typeof(EventEntity).GetProperty("EntityUInt16Value", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EventEntity).GetField("<EntityUInt16Value>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var entityUInt32Value = runtimeEntityType.AddProperty(
                "EntityUInt32Value",
                typeof(uint?),
                propertyInfo: typeof(EventEntity).GetProperty("EntityUInt32Value", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EventEntity).GetField("<EntityUInt32Value>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var entityUInt64Value = runtimeEntityType.AddProperty(
                "EntityUInt64Value",
                typeof(ulong?),
                propertyInfo: typeof(EventEntity).GetProperty("EntityUInt64Value", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EventEntity).GetField("<EntityUInt64Value>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var isLast = runtimeEntityType.AddProperty(
                "IsLast",
                typeof(bool),
                propertyInfo: typeof(EventEntity).GetProperty("IsLast", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EventEntity).GetField("<IsLast>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var userId = runtimeEntityType.AddProperty(
                "UserId",
                typeof(string),
                propertyInfo: typeof(EventEntity).GetProperty("UserId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EventEntity).GetField("<UserId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 255);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "EventEntity");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
