// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Nestor.Db.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Turtle.CompiledModels
{
    public static class EventEntityUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref long Id(EventEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<CreatedAt>k__BackingField")]
        public static extern ref DateTimeOffset CreatedAt(EventEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EntityBooleanValue>k__BackingField")]
        public static extern ref bool? EntityBooleanValue(EventEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EntityByteArrayValue>k__BackingField")]
        public static extern ref byte[] EntityByteArrayValue(EventEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EntityByteValue>k__BackingField")]
        public static extern ref byte? EntityByteValue(EventEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EntityCharValue>k__BackingField")]
        public static extern ref char? EntityCharValue(EventEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EntityDateOnlyValue>k__BackingField")]
        public static extern ref DateOnly? EntityDateOnlyValue(EventEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EntityDateTimeOffsetValue>k__BackingField")]
        public static extern ref DateTimeOffset? EntityDateTimeOffsetValue(EventEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EntityDateTimeValue>k__BackingField")]
        public static extern ref DateTime? EntityDateTimeValue(EventEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EntityDecimalValue>k__BackingField")]
        public static extern ref decimal? EntityDecimalValue(EventEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EntityDoubleValue>k__BackingField")]
        public static extern ref double? EntityDoubleValue(EventEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EntityGuidValue>k__BackingField")]
        public static extern ref Guid? EntityGuidValue(EventEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EntityId>k__BackingField")]
        public static extern ref Guid EntityId(EventEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EntityInt16Value>k__BackingField")]
        public static extern ref short? EntityInt16Value(EventEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EntityInt32Value>k__BackingField")]
        public static extern ref int? EntityInt32Value(EventEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EntityInt64Value>k__BackingField")]
        public static extern ref long? EntityInt64Value(EventEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EntityProperty>k__BackingField")]
        public static extern ref string EntityProperty(EventEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EntitySByteValue>k__BackingField")]
        public static extern ref sbyte? EntitySByteValue(EventEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EntitySingleValue>k__BackingField")]
        public static extern ref float? EntitySingleValue(EventEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EntityStringValue>k__BackingField")]
        public static extern ref string EntityStringValue(EventEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EntityTimeOnlyValue>k__BackingField")]
        public static extern ref TimeOnly? EntityTimeOnlyValue(EventEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EntityTimeSpanValue>k__BackingField")]
        public static extern ref TimeSpan? EntityTimeSpanValue(EventEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EntityType>k__BackingField")]
        public static extern ref string EntityType(EventEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EntityUInt16Value>k__BackingField")]
        public static extern ref ushort? EntityUInt16Value(EventEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EntityUInt32Value>k__BackingField")]
        public static extern ref uint? EntityUInt32Value(EventEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EntityUInt64Value>k__BackingField")]
        public static extern ref ulong? EntityUInt64Value(EventEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TransactionId>k__BackingField")]
        public static extern ref Guid TransactionId(EventEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UserId>k__BackingField")]
        public static extern ref string UserId(EventEntity @this);
    }
}
