// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Nestor.Db.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Turtle.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class MigrationEntityEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Nestor.Db.Models.MigrationEntity",
                typeof(MigrationEntity),
                baseEntityType,
                propertyCount: 2,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(MigrationEntity).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MigrationEntity).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.SetGetter(
                int (MigrationEntity instance) => MigrationEntityUnsafeAccessors.Id(instance),
                bool (MigrationEntity instance) => ((object)MigrationEntityUnsafeAccessors.Id(instance)).Equals(((object)(0))));
            id.SetSetter(
                MigrationEntity (MigrationEntity instance, int value) =>
                {
                    MigrationEntityUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                MigrationEntity (MigrationEntity instance, int value) =>
                {
                    MigrationEntityUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                int (IInternalEntry entry) => MigrationEntityUnsafeAccessors.Id(((MigrationEntity)(entry.Entity))),
                int (IInternalEntry entry) => MigrationEntityUnsafeAccessors.Id(((MigrationEntity)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(id, 0),
                int (IInternalEntry entry) => ((InternalEntityEntry)(entry)).ReadRelationshipSnapshotValue<int>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: -1);
            id.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<int>(id));
            id.SetComparer(new ValueComparer<int>(
                bool (int c1, int c2) => ((object)c1).Equals(((object)(c2))),
                int (int c) => ((object)c).GetHashCode(),
                int (int c) => c));

            var sql = runtimeEntityType.AddProperty(
                "Sql",
                typeof(string),
                propertyInfo: typeof(MigrationEntity).GetProperty("Sql", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MigrationEntity).GetField("<Sql>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            sql.SetGetter(
                string (MigrationEntity instance) => MigrationEntityUnsafeAccessors.Sql(instance),
                bool (MigrationEntity instance) => MigrationEntityUnsafeAccessors.Sql(instance) == null);
            sql.SetSetter(
                MigrationEntity (MigrationEntity instance, string value) =>
                {
                    MigrationEntityUnsafeAccessors.Sql(instance) = value;
                    return instance;
                });
            sql.SetMaterializationSetter(
                MigrationEntity (MigrationEntity instance, string value) =>
                {
                    MigrationEntityUnsafeAccessors.Sql(instance) = value;
                    return instance;
                });
            sql.SetAccessors(
                string (IInternalEntry entry) => MigrationEntityUnsafeAccessors.Sql(((MigrationEntity)(entry.Entity))),
                string (IInternalEntry entry) => MigrationEntityUnsafeAccessors.Sql(((MigrationEntity)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(sql, 1),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(sql));
            sql.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            sql.TypeMapping = SqliteStringTypeMapping.Default;
            sql.SetComparer(new ValueComparer<string>(
                bool (string c1, string c2) => c1 == c2,
                int (string c) => ((object)c).GetHashCode(),
                string (string c) => c));

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var sql = runtimeEntityType.FindProperty("Sql");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<int>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<int>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((MigrationEntity)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int, string>(((ValueComparer<int>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(id)), (source.GetCurrentValue<string>(sql) == null ? null : ((ValueComparer<string>)(((IProperty)sql).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(sql))))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => Snapshot.Empty);
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((MigrationEntity)(source.Entity));
                    return ((ISnapshot)(new Snapshot<int>(((ValueComparer<int>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<int>(id)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 2,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 2,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 0));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Migrations");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
