// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Nestor.Db.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Turtle.CompiledModels
{
    public static class MigrationEntityUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref int Id(MigrationEntity @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Sql>k__BackingField")]
        public static extern ref string Sql(MigrationEntity @this);
    }
}
