// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Turtle.CompiledModels
{
    public partial class TurtleDbContextModel
    {
        private TurtleDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("1e580e0c-89ad-405c-8624-49392368786a"), entityTypeCount: 3)
        {
        }

        partial void Initialize()
        {
            var eventEntity = EventEntityEntityType.Create(this);
            var migrationEntity = MigrationEntityEntityType.Create(this);
            var credentialEntity = CredentialEntityEntityType.Create(this);

            EventEntityEntityType.CreateAnnotations(eventEntity);
            MigrationEntityEntityType.CreateAnnotations(migrationEntity);
            CredentialEntityEntityType.CreateAnnotations(credentialEntity);

            AddAnnotation("ProductVersion", "10.0.1");
        }
    }
}
