// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Turtle;
using Turtle.Services;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(TurtleDbContext), typeof(TurtleDbContextModel))]
